
[mobs]
	blacklist = ["aether:sun_spirit", "blue_skies:summoner", "blue_skies:alchemist", "blue_skies:arachnarch", "blue_skies:starlit_crusher"]
	whitelist = []
	always_show_level = false
	show_level_when_looking_at = true
	exp_bonus_per_level = 0.1
	hidden_levels = []

[attributes]
	attribute_bonuses = [["minecraft:generic.movement_speed", 1.0E-5], ["minecraft:generic.flying_speed", 1.0E-5], ["minecraft:generic.attack_damage", 0.14], ["minecraft:generic.armor", 0.09], ["minecraft:generic.max_health", 0.11], ["autoleveling:monster.projectile_damage_bonus", 0.07], ["autoleveling:monster.explosion_damage_bonus", 0.1]]

[default_leveling_settings]
	starting_level = 1
	max_level = 0
	levels_per_distance = 0.012
	levels_per_deepness = 0.01
	random_level_bonus = 0
	levels_per_day = 0.0
	level_power_per_distance = 0.0
	level_power_per_deepness = 0.0

